/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Carrera;

import javax.swing.JLabel;

/**
 *
 * @author jccr_
 */
public class frameCompets extends javax.swing.JFrame {


   public frameCompets() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Compets");
    }
    public JLabel getCat(){
        return Cat;
    }
    public JLabel getDog(){
        return Dog;
    }
    public JLabel getMeta(){
        return Meta;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Carrera = new javax.swing.JPanel();
        Meta = new javax.swing.JLabel();
        Dog = new javax.swing.JLabel();
        Cat = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Dialog", 2, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 204, 255));
        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 740, 120, 50));

        Carrera.setOpaque(false);

        Meta.setBackground(new java.awt.Color(0, 0, 0));

        Dog.setIcon(new javax.swing.ImageIcon("C:\\Users\\jccr_\\Pictures\\luffi (1).png")); // NOI18N

        Cat.setIcon(new javax.swing.ImageIcon("C:\\Users\\jccr_\\Documents\\NetBeansProjects\\Compets\\src\\Image\\manchas.png")); // NOI18N

        javax.swing.GroupLayout CarreraLayout = new javax.swing.GroupLayout(Carrera);
        Carrera.setLayout(CarreraLayout);
        CarreraLayout.setHorizontalGroup(
            CarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CarreraLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(CarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Cat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Dog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1014, Short.MAX_VALUE)
                .addComponent(Meta, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        CarreraLayout.setVerticalGroup(
            CarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CarreraLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(Cat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Dog)
                .addGap(107, 107, 107))
            .addGroup(CarreraLayout.createSequentialGroup()
                .addComponent(Meta, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(Carrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 1250, 460));

        Fondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\jccr_\\Documents\\NetBeansProjects\\Compets\\src\\Image\\Fondo 2.jpeg")); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        Cat.setLocation(0,Cat.getLocation().y);
        Dog.setLocation(0,Dog.getLocation().y);
        
        Compets cat=new Compets(Cat,this);
        Compets dog=new Compets(Dog,this);
        
        cat.start();
        dog.start();
    }                                        

    public static void main(String args[]) {
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameCompets().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Carrera;
    private javax.swing.JLabel Cat;
    private javax.swing.JLabel Dog;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Meta;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
